In [1]:
import numpy as np

In [2]:
np.version.full_version

'1.10.1'

In [3]:
a=np.array([0,1,2,3,4])

In [4]:
a

array([0, 1, 2, 3, 4])

In [5]:
a.ndim

1

In [6]:
a.shape

(5L,)

In [9]:
a=np.array([0,1,2,3,4,5])

In [10]:
a.shape

(6L,)

In [11]:
b=a.reshape(3,2)

In [12]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [13]:
b[1][0]=77

In [14]:
b

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [15]:
a

array([ 0,  1, 77,  3,  4,  5])

In [16]:
c=a.reshape(3,2).copy()

In [17]:
c

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [18]:
c[0][0]=-99

In [19]:
c

array([[-99,   1],
       [ 77,   3],
       [  4,   5]])

In [20]:
d=np.array([1,2,3,4,5])

In [21]:
d*2

array([ 2,  4,  6,  8, 10])

In [22]:
d**2

array([ 1,  4,  9, 16, 25])

In [23]:
d

array([1, 2, 3, 4, 5])