In [1]:
import numpy as np

In [2]:
my_list1=[1,2,3,4]

In [3]:
my_array1=np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4])

In [6]:
my_list2=[11,22,33,44]

In [7]:
my_list=my_list1+my_list2

In [8]:
my_list

[1, 2, 3, 4, 11, 22, 33, 44]

In [13]:
my_list=[my_list1,my_list2]

In [14]:
my_list

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [15]:
my_array2=np.array(my_list)

In [16]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [17]:
my_array2.shape

(2L, 4L)

In [18]:
my_array2.dtype

dtype('int32')

In [20]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [21]:
my_zeros_array=np.zeros(5)

In [22]:
my_zeros_array

array([ 0.,  0.,  0.,  0.,  0.])

In [24]:
my_zeros_array.dtype

dtype('float64')

In [25]:
my_ones_array=np.ones([5,5])

In [26]:
my_ones_array

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [27]:
my_ones_array.dtype

dtype('float64')

In [28]:
my_empty_array=np.empty(5)

In [29]:
my_empty_array.dtype

dtype('float64')

In [30]:
my_empty_array

array([ 0.,  0.,  0.,  0.,  0.])

In [31]:
id_matrix=np.eye(5)

In [32]:
id_matrix

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [33]:
id_matrix.dtype

dtype('float64')

In [34]:
array_arange=np.arange(5)

In [35]:
array_arange

array([0, 1, 2, 3, 4])

In [36]:
array_arange=np.arange(5,50,2)

In [37]:
array_arange

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])