In [1]:
import numpy as np

In [2]:
arr=np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A

array([ 0.80868432, -1.37229851, -0.51937708, -0.64300295, -0.73399539,
        0.69145433, -1.45701811, -1.85412555,  0.31029015,  1.0786373 ])

In [8]:
B=np.random.randn(10)

In [9]:
B

array([ 0.41826624,  0.9305901 ,  0.2867955 ,  1.48673544,  0.05448766,
       -0.89126954,  1.49377977, -0.87357821, -0.90400954, -0.53090138])

In [10]:
#Binary Functions
np.add(A,B)

array([ 1.22695055, -0.44170841, -0.23258158,  0.84373249, -0.67950772,
       -0.19981521,  0.03676166, -2.72770375, -0.59371938,  0.54773592])

In [11]:
np.maximum(A,B)

array([ 0.80868432,  0.9305901 ,  0.2867955 ,  1.48673544,  0.05448766,
        0.69145433,  1.49377977, -0.87357821,  0.31029015,  1.0786373 ])

In [12]:
np.minimum(A,B)

array([ 0.41826624, -1.37229851, -0.51937708, -0.64300295, -0.73399539,
       -0.89126954, -1.45701811, -1.85412555, -0.90400954, -0.53090138])

Univeral functions can be seen on scipy webpage.