In [1]:
import numpy as np
a=np.array([5,67,43,76,2,21])
print a

[ 5 67 43 76  2 21]


In [3]:
a=np.array([[4,5,8,4],[6,3,2,1],[8,6,4,3]])
print a

[[4 5 8 4]
 [6 3 2 1]
 [8 6 4 3]]


In [9]:
data=np.random.randn(2,3)
print data
print data*10
print data+data

[[-0.6600798   0.73298028  0.26716132]
 [-0.83352622  1.37199579  0.37885148]]
[[ -6.60079804   7.32980276   2.67161316]
 [ -8.33526218  13.71995789   3.78851485]]
[[-1.32015961  1.46596055  0.53432263]
 [-1.66705244  2.74399158  0.75770297]]


In [10]:
print data.shape

(2, 3)


In [11]:
print data.dtype

float64


In [12]:
data1=[6,7.5,8,0,1]
arr1=np.array(data1)
print arr1

[ 6.   7.5  8.   0.   1. ]


In [13]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
print arr2
print arr2.ndim
print arr2.shape

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


In [15]:
print type(arr2.ndim)
print type(arr2.shape)

<type 'int'>
<type 'tuple'>


In [16]:
print arr2.shape[0]
print arr2.shape[1]

2
4


In [17]:
data2=[[[1]]]
arr2=np.array(data2)
print arr2
print arr2.ndim
print arr2.shape

[[[1]]]
3
(1, 1, 1)


In [18]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [19]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [20]:
np.empty((2,3,2))

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [21]:
arr=np.array([1.,2.,3.])
print arr
print arr*arr
print arr-arr
print 1/arr
print arr**0.5

[ 1.  2.  3.]
[ 1.  4.  9.]
[ 0.  0.  0.]
[ 1.          0.5         0.33333333]
[ 1.          1.41421356  1.73205081]


In [22]:
a=np.array([True],dtype=np.int64)
print a
print a.dtype

[1]
int64


In [23]:
a=np.array([True],dtype=np.bool)
print a
print a.dtype

[ True]
bool


In [24]:
arr=np.array([3.7,-1.2,-2.6])
print arr
print arr.astype(np.int32)

[ 3.7 -1.2 -2.6]
[ 3 -1 -2]


In [29]:
numeric_strings=np.array(['1.25','-9.6','42'],dtype=np.string_)
print numeric_strings
print numeric_strings.astype(float)

['1.25' '-9.6' '42']
[  1.25  -9.6   42.  ]


In [30]:
arr=np.arange(10)
print arr

[0 1 2 3 4 5 6 7 8 9]


In [31]:
print arr[5]

5


In [32]:
print arr[5:8]

[5 6 7]


In [33]:
arr[5:8]=12
print arr

[ 0  1  2  3  4 12 12 12  8  9]


In [36]:
arr_slice=arr[5:8]
arr_slice[1]=12345
print arr_slice
print arr

[   64 12345    64]
[    0     1     2     3     4    64 12345    64     8     9]


In [37]:
arr_slice[:]=64
print arr

[ 0  1  2  3  4 64 64 64  8  9]


In [38]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print arr2d[2]
print arr2d[0][2]
print arr2d[0,2]

[7 8 9]
3
3


In [45]:
arr3d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print arr3d
print arr3d[0]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 2 3]


In [46]:
arr=np.arange(10)
print arr
print arr[1:6]

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]


In [2]:
import numpy as np
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print arr2d
print arr2d[:2]
print arr2d[:2,1:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


In [4]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print arr2d[1,:2]
print arr2d[2,:1]

[4 5]
[7]


In [5]:
arr=np.empty((8,4))
for i in range(8):
    arr[i]=i
print arr

[[ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]
 [ 4.  4.  4.  4.]
 [ 5.  5.  5.  5.]
 [ 6.  6.  6.  6.]
 [ 7.  7.  7.  7.]]


In [6]:
print arr[[4,3,0,6]]

[[ 4.  4.  4.  4.]
 [ 3.  3.  3.  3.]
 [ 0.  0.  0.  0.]
 [ 6.  6.  6.  6.]]


In [7]:
print arr[[-3,-5,-7]]

[[ 5.  5.  5.  5.]
 [ 3.  3.  3.  3.]
 [ 1.  1.  1.  1.]]


In [9]:
arr=np.arange(15).reshape((3,5))
print arr

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [10]:
print arr.shape

(3, 5)


In [13]:
print arr.ndim

2


In [14]:
print arr.T

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [16]:
print arr.shape
print arr.T.shape

(3, 5)
(5, 3)


In [17]:
arr=np.arange(9).reshape((3,3))
print arr
print arr.shape

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


In [18]:
print np.dot(arr.T,arr)

[[45 54 63]
 [54 66 78]
 [63 78 93]]


In [19]:
arr=np.arange(9).reshape((3,3))
print arr
print arr*arr

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [20]:
arr=np.arange(5)
print arr
print np.sqrt(arr)
print np.exp(arr)

[0 1 2 3 4]
[ 0.          1.          1.41421356  1.73205081  2.        ]
[  1.           2.71828183   7.3890561   20.08553692  54.59815003]


In [24]:
x=np.random.randn(4)
y=np.random.randn(4)
print x
print y
print np.minimum(x,y)

[ 0.50359583 -0.12873363  0.10106283 -1.56389047]
[-0.9868036   0.59119756 -0.11531069  0.1814369 ]
[-0.9868036  -0.12873363 -0.11531069 -1.56389047]


In [25]:
x=np.random.randn(4)
y=np.random.randn(4)
print x
print y
print np.add(x,y)

[-0.46536475 -0.46669146  0.46379356 -0.81642325]
[ 0.10422849 -0.58900224  0.44653314  1.12359194]
[-0.36113626 -1.0556937   0.9103267   0.30716869]


In [26]:
a=[1,2,3]
b=[10,20,30]
zipAB=zip(a,b)
print zipAB

[(1, 10), (2, 20), (3, 30)]


In [27]:
a=[1,2,3]
b=[10,20,30]
c=[True,False,True]
zipABC=zip(a,b,c)
print zipABC

[(1, 10, True), (2, 20, False), (3, 30, True)]


In [28]:
result=[(x,y,z) for x,y,z in zip(a,b,c)]
print result

[(1, 10, True), (2, 20, False), (3, 30, True)]


In [32]:
result=[x if z else y for x,y,z in zip(a,b,c)]
print result
print type(result)

[1, 20, 3]
<type 'list'>


In [31]:
print np.where(c,a,b)
print type(np.where)

[ 1 20  3]
<type 'builtin_function_or_method'>


In [3]:
a=[1,2,3]
b=[10,20,30]
c=[True,False,True]
result =[(x if z else y) for x,y,z in zip(a,b,c)]
print result

[1, 20, 3]


In [4]:
type(result)

list

In [7]:
import numpy as np
arr=np.random.randn(4,4)
print arr
print np.where(arr>0,2,-2)

[[-0.76814309 -0.3232349   1.04581048  0.26287955]
 [-1.48182589  3.30072431 -1.17903787 -1.0674473 ]
 [-1.91487061 -0.18218887 -0.0222159  -0.45539752]
 [ 0.44216152 -3.13713746 -2.2177612  -0.04514072]]
[[-2 -2  2  2]
 [-2  2 -2 -2]
 [-2 -2 -2 -2]
 [ 2 -2 -2 -2]]


In [9]:
arr=np.random.randn(4,4)
print arr
print np.where(arr>0,2,arr)

[[-0.13891892 -0.45788166 -2.82004371 -0.117766  ]
 [ 1.28126907 -0.99109915 -0.57890895 -0.40825588]
 [-0.04052263  0.06315857  0.5932093   0.49745262]
 [-0.11871752  1.25013183 -0.81285607  0.29389138]]
[[-0.13891892 -0.45788166 -2.82004371 -0.117766  ]
 [ 2.         -0.99109915 -0.57890895 -0.40825588]
 [-0.04052263  2.          2.          2.        ]
 [-0.11871752  2.         -0.81285607  2.        ]]


In [12]:
arr=np.random.randn(5,4)
print arr
print "mean",arr.mean()
print "sum",arr.sum()

[[ 0.74381257 -1.68290675 -0.21969393  0.69572497]
 [-1.65412199 -1.5661736  -2.21984613  0.05410448]
 [ 0.54682368 -0.02899422 -1.25251889  1.65707248]
 [ 0.98516462  1.72920547  0.6785407   0.93735263]
 [ 0.10883812  1.941117    0.83107553 -0.76682971]]
mean 0.0758873519525
sum 1.51774703905


In [16]:
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])
print arr
print arr.mean(axis=0)
print arr.mean(axis=1)
print arr.sum(0)
print arr.sum(1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 3.  4.  5.]
[ 1.  4.  7.]
[ 9 12 15]
[ 3 12 21]


In [17]:
arr=np.array([[0,1,2,],[3,4,5],[6,7,8]])
print arr
print arr.cumsum(0)
print arr.cumsum(1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]


In [18]:
print arr
print arr.cumprod(0)
print arr.cumprod(1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 0  4 10]
 [ 0 28 80]]
[[  0   0   0]
 [  3  12  60]
 [  6  42 336]]


In [19]:
arr=np.random.randn(10)
print arr
print (arr>0).sum()

[ 0.01028659  0.00840879  0.51717926  1.54260068  0.62081618  0.11162744
 -0.84926169  0.59941416  0.53529272  1.54545266]
9


In [21]:
arr=np.random.randn(4)
print arr
arr.sort()
print arr

[-2.45718853 -0.43108375  1.67913322 -1.95990223]
[-2.45718853 -1.95990223 -0.43108375  1.67913322]


In [22]:
arr=np.random.randn(2,3)
print arr
arr.sort(0)
print arr
arr.sort(1)
print arr

[[-0.55986531  0.30558875 -0.67353875]
 [-0.42235478  0.15701457 -1.31814854]]
[[-0.55986531  0.15701457 -1.31814854]
 [-0.42235478  0.30558875 -0.67353875]]
[[-1.31814854 -0.55986531  0.15701457]
 [-0.67353875 -0.42235478  0.30558875]]
