In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
arr1=np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1=Series([0,1,2],index=['T','U','V'])
ser2=Series([3,4],index=['X','Y'])
ser1

T    0
U    1
V    2
dtype: int64

In [7]:
ser2

X    3
Y    4
dtype: int64

In [8]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2],axis=1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [10]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [11]:
d_frame1=DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
d_frame2=DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [12]:
d_frame1

X         Y         Z
0  0.860932  0.930548 -0.748056
1  0.624333  0.985103 -0.441738
2  1.452239  0.909065 -1.252677
3  0.435828  0.792643 -1.480059

In [13]:
d_frame2

Y         Q         X
0 -0.792635  0.793364  3.109746
1  0.624977  0.559490 -0.246833
2  1.489704  0.415293  1.076724

In [14]:
pd.concat([d_frame1,d_frame2])

Q         X         Y         Z
0       NaN  0.860932  0.930548 -0.748056
1       NaN  0.624333  0.985103 -0.441738
2       NaN  1.452239  0.909065 -1.252677
3       NaN  0.435828  0.792643 -1.480059
0  0.793364  3.109746 -0.792635       NaN
1  0.559490 -0.246833  0.624977       NaN
2  0.415293  1.076724  1.489704       NaN

In [15]:
pd.concat([d_frame1,d_frame2],ignore_index=1)

Q         X         Y         Z
0       NaN  0.860932  0.930548 -0.748056
1       NaN  0.624333  0.985103 -0.441738
2       NaN  1.452239  0.909065 -1.252677
3       NaN  0.435828  0.792643 -1.480059
4  0.793364  3.109746 -0.792635       NaN
5  0.559490 -0.246833  0.624977       NaN
6  0.415293  1.076724  1.489704       NaN