In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
dframe = DataFrame(np.arange(16).reshape(4,4))

In [3]:
blender=np.random.permutation(4)

In [4]:
blender

array([2, 3, 1, 0])

In [5]:
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [7]:
dframe.take(blender,axis=1)

2   3   1   0
0   2   3   1   0
1   6   7   5   4
2  10  11   9   8
3  14  15  13  12

In [8]:
box = np.array([1,2,3])

In [9]:
box

array([1, 2, 3])

In [10]:
shaker = np.random.randint(0,len(box),size=10)

In [11]:
shaker

array([0, 1, 0, 2, 0, 0, 0, 1, 1, 0])

In [12]:
hand_grabs = box.take(shaker)

In [13]:
hand_grabs

array([1, 2, 1, 3, 1, 1, 1, 2, 2, 1])